Add tree
vokarl/capstone pull request #7
Opened 2023-06-30 09:20 UTC by vokarl

2023-06-30 13:33 UTC, mpagels requested changes
Hey Karl, very good start here.
Found a semantic issue. Pls review.

Keep up the good work!

2023-06-30 13:33 UTC, mpagels commented on components/TreeList.js
> +import { allTrees } from "../resources/treearray";
is this working now?

2023-06-30 13:33 UTC, mpagels commented on pages/addpile/index.js
> +`;
Hey check here the semantic. You're using an `ul` element as a parent element. Semantic would be correct, that a `li` element is following. And you created a `ListItem` that you are not using.

2023-06-30 13:33 UTC, mpagels commented on pages/index.js
> +      <AddPile />
You're using a page component inside a page component. That could be a problem.

2023-06-30 13:33 UTC, mpagels commented on pages/index.js
> +      <AddPile />
Would recommend refactoring the `addPile` to the component folder.

2023-06-30 13:33 UTC, mpagels commented on pages/treelist/index.js
> +    Oxygen, Ubuntu, Cantarell, "Open Sans", "Helvetica Neue", sans-serif;
Might be a good idea to make the font global available in the global styles to omit these lines here.

2023-07-03 09:15 UTC, sebastianwel commented
Hey Karl, reviewed all your changes and saw that you implemented Martins' changes correctly 🤘 Vercel looks also good, so nothing to add here from my side! 😁

2023-07-03 09:15 UTC, sebastianwel approved these changes

2023-07-03 13:22 UTC, vokarl commented
Thanks for the review👋

2023-07-04 11:29 UTC, merged